language: php
php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/codacycoverage clover report/clover.xml
