language: php
php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpstan analyse --level 4 --configuration phpstan.neon src tests

after_script:
  - vendor/bin/codacycoverage clover report/clover.xml
