language: php
php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --prefer-dist --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]]; then vendor/bin/phpstan analyse --level 4 --configuration phpstan.neon src tests; fi

after_script:
  - vendor/bin/codacycoverage clover report/clover.xml
